import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../services/api';

export default function CreatePost() {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const [tone, setTone] = useState('creative'); const [caption, setCaption] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const input = useRef(null); const navigate = useNavigate();
  useEffect(() => () => preview && URL.revokeObjectURL(preview), [preview]);
  function choose(selected) { if (!selected) return; if (!selected.type.startsWith('image/')) return setError('Choose a JPG, PNG, or WEBP image.'); if (selected.size > 5 * 1024 * 1024) return setError('Images must be under 5MB.'); setError(''); setCaption(''); setFile(selected); setPreview(URL.createObjectURL(selected)); }
  async function submit(event) { event.preventDefault(); if (busy) return; if (!file) return setError('Select an image first.'); setBusy(true); setError(''); const form = new FormData(); form.append('image', file); form.append('tone', tone); try { const result = await api.createPost(form); setCaption(result.post.caption); setFile(null); setPreview(''); if (input.current) input.current.value = ''; } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="page narrow-page"><header className="page-header"><div><span className="kicker">New work</span><h1>Give the image a voice.</h1><p className="muted">Upload a moment. We’ll return a caption worth keeping.</p></div><Link to="/history" className="quiet-link">View archive →</Link></header><form onSubmit={submit} className="create-layout"><div className={`dropzone ${preview ? 'has-preview' : ''}`} role="button" tabIndex="0" aria-label="Choose an image" onKeyDown={e => (e.key === 'Enter' || e.key === ' ') && input.current?.click()} onClick={() => input.current?.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); choose(e.dataTransfer.files[0]); }}>{preview ? <img src={preview} alt="Selected preview" /> : <div className="drop-prompt"><span className="upload-mark">↑</span><strong>Drop an image here</strong><span>or browse from your device · max 5MB</span></div>}<input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => choose(e.target.files[0])} hidden /></div><div className="create-controls"><label htmlFor="caption-mood">Caption mood<select id="caption-mood" value={tone} onChange={e => setTone(e.target.value)}><option value="creative">Bold & playful</option><option value="professional">Clean & polished</option><option value="energetic">High-energy</option><option value="minimal">Simple & elegant</option></select></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={busy || !file}>{busy ? 'Uploading & thinking...' : 'Generate caption →'}</button>{caption && <div className="result-note" role="status"><span className="kicker">Your caption</span><p>{caption}</p><button type="button" className="text-button" onClick={() => navigate('/history')}>Open in history ↗</button></div>}</div></form></div>;
}
