import { useEffect, useState } from 'react';
import { api } from '../services/api';
import PostCard from '../components/PostCard';

export default function History() {
  const [data, setData] = useState({ posts: [], pagination: {} }); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [deletingId, setDeletingId] = useState('');
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); api.posts({ page, limit: 8, search }, { signal: controller.signal }).then(setData).catch(err => { if (err.name !== 'AbortError') setError(err.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [page, search]);
  async function remove(id) { if (!window.confirm('Delete this caption and its post?')) return; setDeletingId(id); try { await api.deletePost(id); const nextTotal = Math.max(0, (data.pagination.total || 0) - 1); const nextPages = Math.max(1, Math.ceil(nextTotal / (data.pagination.limit || 8))); if (page > nextPages) setPage(nextPages); else setData(current => ({ ...current, posts: current.posts.filter(post => post.id !== id), pagination: { ...current.pagination, total: nextTotal, pages: nextPages } })); } catch (err) { setError(err.message); } finally { setDeletingId(''); } }
  return <div className="page"><header className="page-header"><div><span className="kicker">The archive</span><h1>Caption history.</h1><p className="muted">Every image, idea, and small act of publishing.</p></div><div className="history-count">{data.pagination.total ?? 0} posts</div></header><div className="search-bar"><span aria-hidden="true">⌕</span><label className="sr-only" htmlFor="caption-search">Search your captions</label><input id="caption-search" value={search} onChange={e => { setPage(1); setSearch(e.target.value); }} placeholder="Search your captions..." /></div>{error && <div className="form-error" role="alert">{error}</div>}{loading ? <div className="screen-state inner">Loading your archive...</div> : data.posts.length ? <><div className="post-grid">{data.posts.map(post => <PostCard key={post.id} post={post} deleting={deletingId === post.id} onDelete={remove} />)}</div><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(p => p - 1)}>← Previous</button><span>Page {data.pagination.page || page} of {Math.max(1, data.pagination.pages || 1)}</span><button disabled={page >= (data.pagination.pages || 1)} onClick={() => setPage(p => p + 1)}>Next →</button></div></> : <div className="empty-state"><span className="empty-icon">⌕</span><h3>{search ? 'No captions found.' : 'Nothing in the archive yet.'}</h3><p>{search ? 'Try a different phrase.' : 'Your generated captions will live here.'}</p></div>}</div>;
}
